DELETE
FROM FILM_LIKES;
DELETE
FROM FILM_GENRE;
DELETE
FROM FRIENDS;
DELETE
FROM USERS;
DELETE
FROM FILMS;
/*
ALTER TABLE USERS
    ALTER COLUMN USER_ID RESTART WITH 1;
ALTER TABLE FILMS
    ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE FRIENDS
    ALTER COLUMN USER_ID RESTART WITH 1;
ALTER TABLE FRIENDS
    ALTER COLUMN FRIEND_ID RESTART WITH 1;
ALTER TABLE FILM_GENRE
    ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE FILM_LIKES
    ALTER COLUMN USER_ID RESTART WITH 1;
ALTER TABLE FILM_LIKES
    ALTER COLUMN FILM_ID RESTART WITH 1;
*/
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (1, 'Комедия');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (2, 'Драма');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (3, 'Мультфильм');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (4, 'Триллер');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (5, 'Документальный');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (6, 'Боевик');

MERGE INTO MPA (MPA_ID, NAME) VALUES (1, 'G');
MERGE INTO MPA (MPA_ID, NAME) VALUES (2, 'PG');
MERGE INTO MPA (MPA_ID, NAME) VALUES (3, 'PG-13');
MERGE INTO MPA (MPA_ID, NAME) VALUES (4, 'R');
MERGE INTO MPA (MPA_ID, NAME) VALUES (5, 'NC-17');